apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-data-pvc
  namespace: student-da25m601
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-checkpoint-pvc
  namespace: student-da25m601
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi