apiVersion: batch/v1
kind: Job
metadata:
  name: model-training
  namespace: student-da25m601
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: training
          image: mlops-train:v1
          imagePullPolicy: IfNotPresent

          env:
            - name: TRAINING_CONFIG
              value: /app/configs/training_config.yaml

          resources:
            requests:
              cpu: "2"
              memory: "4Gi"

          volumeMounts:
            - name: training-config
              mountPath: /app/configs
              readOnly: true

            - name: training-data
              mountPath: /app/data

            - name: model-checkpoints
              mountPath: /app/checkpoints

      volumes:
        - name: training-config
          configMap:
            name: training-config

        - name: training-data
          persistentVolumeClaim:
            claimName: training-data-pvc

        - name: model-checkpoints
          persistentVolumeClaim:
            claimName: model-checkpoint-pvc