FROM python:3.11-slim AS base

WORKDIR /app

COPY requirements/train.txt .
#RUN pip install --no-cache-dir -r train.txt
RUN pip install --no-cache-dir \
    torch==2.10.0+cpu \
    torchvision==0.25.0+cpu \
    --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir PyYAML==6.0.3

FROM base AS training

COPY src/ ./src/
COPY configs/ ./configs/

ENV PYTHONUNBUFFERED=1
ENV TRAINING_CONFIG=/app/configs/training_config.yaml

ENTRYPOINT ["python", "-m", "src.train"]
